log_file: "direct_call_llm_deepseek.log"

llm_provider: "deepseek"
llm:
  model: "deepseek"
  api_key_env: "123"
  base_url: "http://192.168.1.101:60102/v1"
  context_length: 4096

result_filename: "deepseek.json"
dataset_base: "/Data1/hxq/datasets/incremental_packages_dynamic_capping_subset"
start_month: "2022-01"
end_month: "2024-12"
incremental_start_month: "2024-01"
incremental_end_month: "2024-12"
