log_file: "direct_call_llm_llama2.log"

llm_provider: "llama2"
llm:
  model: "llama-2"
  api_key_env: "123"
  base_url: "http://192.168.1.101:60103/v1"
  context_length: 4096

result_filename: "llama2.json"
dataset_base: "${DATA_ROOT}/datasets/incremental_packages_dynamic_capping_subset"
start_month: "2022-01"
end_month: "2024-12"
incremental_start_month: "2024-01"
incremental_end_month: "2024-12"
