log_file: "direct_call_llm_qwen2_5.log"

llm_provider: "qwen2.5-coder-32b"
llm:
  model: "qwen-2.5-coder-32b"
  api_key_env: "123"
  base_url: "http://192.168.1.101:60102/v1"
  context_length: 32768

result_filename: "qwen2_5.json"
dataset_base: "/Data1/hxq/datasets/incremental_packages_dynamic_capping_subset"
start_month: "2022-01"
end_month: "2024-12"
