log_file: "direct_call_llm_llama3.log"

llm_provider: "llama3"
llm:
  model: "llama-3"
  api_key_env: "123"
  base_url: "http://192.168.1.101:60103/v1"
  context_length: 8192

result_filename: "llama3.json"
start_month: "2022-02"
end_month: "2024-12"
