log_file: "direct_call_llm_qwen3_5.log"

llm_provider: "qwen3.5-27b"
llm:
  model: "qwen-3.5-27b"
  api_key_env: "123"
  base_url: "http://192.168.1.101:60101/v1"
  context_length: 163840

result_filename: "qwen3_5_27b.json"
start_month: "2023-03"
end_month: "2024-12"
