# 继承 default.yaml
parent: "default.yaml"

# 增量学习配置
continual_learning:
  memory_per_month: 30
  use_memory: True

# 结果文件配置
results:
  future_month: "CL_unk_memory_30_test_than_train_future_month.json"

# 路径配置
paths:
  prefix: "incremental_unk_memory_30_model_"
