# 继承 default.yaml
parent: "default.yaml"

# 增量学习配置（覆盖 parent 中的配置）
continual_learning:
  memory_per_month: 20
  use_memory: False

# 结果文件配置（覆盖 parent 中的配置）
results:
  future_month: "test_than_train_future_test_results.json"
