# 继承 default.yaml
parent: "default.yaml"

# 增量学习配置（覆盖 parent 中的配置）
continual_learning:
  memory_ratio: 3  # 每训练3个新batch，训练1个记忆库batch

# 结果文件配置（覆盖 parent 中的配置）
results:
  future_month: "CL_unk_memory_ratio_3_test_than_train_future_month.json"
