# direct_call_llm 配置

log_file: "direct_call_llm_deepseek.log"

llm_provider: "deepseek"
llm:
  model: "deepseek"
  api_key_env: "123"
  base_url: "http://192.168.1.101:60102/v1"
  context_length: 4096

# 批量分析时每个包的结果文件名
result_filename: "deepseek.json"

# 增量扫描月份范围
start_month: "2023-12"
end_month: "2024-12"
