parent: "../default.yaml"

llm:
  model_name: "llama-2"
  api_key_env: "123"
  base_url: "http://192.168.1.101:60103/v1"
  context_length: 4096
  synth_rules: true

dataset:
  vocab_dir: "vocab_llama2"
  benign_out: "benign_call_processed_llama2"
  malicious_out: "malicious_call_processed_llama2"
  call_graph_filename: "llama-2_call_graph.json"

continual_learning:
  base_train_months: ["2022-01", "2023-12"]
  incremental_months: ["2024-01", "2024-12"]

results:
  future_month: "CL_unk_test_than_train_future_month_llama2.json"
  base_model_result_file: "base_model_in_future_month_once_llama2.json"

paths:
  models_dir: "./models/llama2"
  results_dir: "../results"
  pretrained_model: "./models/llama2/base_model.pt"
  prefix: "incremental_"
